import type { ServiceCategory } from "./types";

export const eventCatering: ServiceCategory = {
  slug: "event-catering",
  source: "event_catering_page",
  serviceType: "Event Catering",
  meta: {
    title: "Event Catering in Riyadh | Corporate, Wedding & Private Event Catering | SEM",
    description:
      "Request event catering options in Riyadh for corporate events, weddings, conferences and private gatherings. Share your guest count, date and service style — SEM coordinates suitable Saudi-based caterers.",
    keywords: [
      "event catering Riyadh",
      "corporate event catering Riyadh",
      "wedding catering Riyadh",
      "conference catering Saudi Arabia",
      "canapé and reception catering Riyadh",
      "buffet catering for events Riyadh",
      "تموين حفلات الرياض",
    ],
    ogImageAlt: "Formal event dinner table with gold-rimmed tableware, floral centrepiece and candles",
  },
  en: {
    name: "Event Catering",
    hero: {
      badge: "Event Catering · Riyadh",
      title: "Event Catering",
      highlight: "in Riyadh",
      subtitle:
        "Tell us your guest count, event date, venue and preferred service style. SEM coordinates suitable Saudi-based catering partners and brings you options that fit your event — corporate, wedding or private.",
      image: "/services/saudi_gala_table_alcohol_free.webp",
      imageAlt: "Formal event dinner table set with gold-rimmed plates, crystal glasses and a white floral centrepiece in a Riyadh ballroom",
    },
    snapshot: [
      { label: "Service type", value: "Catering coordination" },
      { label: "Best for", value: "Corporate · Weddings · Private" },
      { label: "Location", value: "Riyadh & major Saudi cities" },
      { label: "Quote", value: "Requirement-based" },
    ],
    answer: {
      question: "What does event catering in Riyadh include?",
      answer:
        "Event catering covers the food, beverages, service staff and serving setup for your event. With SEM, you share the event type, date, venue, guest count and service format; SEM matches the brief with suitable Riyadh-based catering partners, requests options and pricing, and presents them in one quotation. The selected caterer prepares and serves the food, while SEM stays your single point of contact.",
    },
    intro: [
      "Catering is usually the largest single line in an event budget and the part guests remember most. The right choice depends less on a menu brochure and more on your event: how many guests, how long they stay, whether they are seated or moving, and what the venue allows.",
      "SEM does not run a kitchen. We qualify your requirements properly and request options from catering partners whose format, capacity and availability suit your date — so you compare relevant proposals rather than generic price lists.",
    ],
    capabilities: {
      heading: "What SEM can coordinate",
      lead: "Every enquiry is matched to partners on format, guest count and date. Typical catering scope includes:",
      items: [
        { icon: "utensils", title: "Menu options & tastings", desc: "Menu proposals aligned to your event and guests, with tastings where the caterer offers them for the booking size." },
        { icon: "layers", title: "Service format", desc: "Plated, buffet, family-style, canapé reception or coffee breaks — chosen around your run-of-show and layout." },
        { icon: "users", title: "Service staff", desc: "Waiters, buffet attendants and beverage staff where the catering partner supplies them in the package." },
        { icon: "coffee", title: "Hospitality stations", desc: "Arabic coffee and dates, tea service, mocktail and juice stations, and refreshment points for long events." },
        { icon: "wrench", title: "Caterer-supplied setup", desc: "Buffet stations, chafing equipment, crockery and cutlery as supplied by the caterer, checked against venue rules." },
        { icon: "leaf", title: "Dietary requirements", desc: "Halal is standard in Saudi Arabia; vegetarian, allergy-aware and other needs are flagged at the request stage." },
      ],
    },
    subServices: {
      heading: "Catering services for every event format",
      lead: "One enquiry covers all of these. Tell us which fits, or let us recommend a format from your brief.",
      items: [
        { title: "Corporate & Conference Catering", desc: "Working lunches, coffee breaks and networking lunches timed around the agenda.", useCase: "Seminars, AGMs, training days", image: "/services/premium_corporate_summit_hero.webp", imageAlt: "Corporate summit lounge with guests seated around coffee tables", href: "/services/conferences" },
        { title: "Wedding Catering", desc: "Seated dinners or buffets for receptions, with service planned per hall where needed.", useCase: "Receptions, engagements, walimah", image: "/services/luxury_wedding_table_setting.webp", imageAlt: "Round wedding reception table with gold charger plates and a rose centrepiece", href: "/services/weddings" },
        { title: "VIP & Majlis Hospitality", desc: "Discreet, higher-touch service with Arabic coffee, dates and plated or passed food.", useCase: "Board dinners, delegations, majlis evenings", image: "/services/vip_private_event_saudi.webp", imageAlt: "Majlis hospitality with a host serving Arabic coffee to seated guests", href: "/services/luxury-vip-events" },
        { title: "Hospitality & Guest Service", desc: "Arabic coffee service, welcome drinks and attended refreshment stations for arrivals.", useCase: "Openings, receptions, heritage venues", image: "/services/diriyah_event_venues.webp", imageAlt: "Evening reception courtyard with an Arabic coffee service station and guests mingling" },
        { icon: "utensils", title: "Executive Meeting Catering", desc: "Plated lunches and boardroom refreshments for leadership meetings." },
        { icon: "coffee", title: "Coffee Break Catering", desc: "Timed morning and afternoon breaks for conferences and workshops." },
        { icon: "layers", title: "Buffet Catering", desc: "Flexible buffets for larger guest counts and staggered arrivals." },
        { icon: "sparkles", title: "Canapés & Finger Food", desc: "Passed canapés and finger food for launches and networking receptions." },
        { icon: "chef", title: "Live Cooking Stations", desc: "Chef-attended stations where the caterer offers them and the venue allows." },
        { icon: "building", title: "Exhibition Catering", desc: "Stand hospitality and team meals across multi-day shows.", href: "/services/exhibitions" },
        { icon: "users", title: "Private Event Catering", desc: "Family gatherings, birthdays and home events with personal service.", href: "/services/birthday-party" },
        { icon: "sun", title: "Outdoor Event Catering", desc: "Gardens, courtyards and outdoor sites — with power, water and heat planned." },
      ],
    },
    flow: {
      heading: "How a catering brief becomes a quote",
      lead: "These five details decide almost everything about a catering proposal.",
      steps: [
        { label: "Guest count", detail: "Drives quantities, staff and equipment" },
        { label: "Event type", detail: "Sets tone, timing and presentation" },
        { label: "Service style", detail: "Plated, buffet, canapés or breaks" },
        { label: "Menu", detail: "Courses, ingredients, dietary needs" },
        { label: "Staffing", detail: "Waiters, attendants, station chefs" },
      ],
    },
    idealFor: {
      heading: "Ideal for",
      items: [
        { title: "Corporate events & gala dinners", desc: "Annual dinners, award nights, client receptions.", href: "/services/corporate-events" },
        { title: "Conferences & seminars", desc: "Breaks, lunch and hospitality on schedule.", href: "/services/conferences" },
        { title: "Weddings & engagements", desc: "Receptions where timing and presentation matter.", href: "/services/weddings" },
        { title: "Exhibitions", desc: "Stand hospitality across show days.", href: "/services/exhibitions" },
        { title: "Openings & launches", desc: "Reception-style catering for brand moments." },
        { title: "Private gatherings", desc: "Majlis evenings, Eid gatherings, birthdays.", href: "/services/birthday-party" },
      ],
    },
    process: {
      heading: "How event catering coordination works",
      items: [
        { title: "Share your brief", desc: "Event type, date, venue, guest count and preferred format — by form or WhatsApp." },
        { title: "We qualify the details", desc: "Service duration, venue kitchen access, staffing and dietary needs." },
        { title: "Partner matching", desc: "Suitable Riyadh-based caterers with availability for your date." },
        { title: "Options & quotation", desc: "Menu and service options in one SEM quotation." },
        { title: "Confirm & coordinate", desc: "Final menu, timings and logistics between you, caterer and venue." },
      ],
    },
    quoteFactors: {
      heading: "What affects event catering pricing?",
      lead: "There is no honest fixed price for event catering — these factors move the cost most:",
      items: [
        { title: "Guest count", desc: "The main driver of food quantity, staffing and equipment." },
        { title: "Service style", desc: "Plated service needs more staff than a buffet; canapés depend on pieces per guest." },
        { title: "Menu selection", desc: "Ingredients, number of courses and premium items." },
        { title: "Service duration", desc: "A two-hour reception and an all-day conference are different briefs." },
        { title: "Venue conditions", desc: "Kitchen access, outdoor setup, loading and venue catering rules." },
        { title: "Staffing & equipment", desc: "Waiters, attendants, stations, crockery and hire items." },
        { title: "Date & season", desc: "Weekends, Ramadan and peak seasons affect availability." },
      ],
    },
    clientChecklist: {
      heading: "What information is needed for a catering quote?",
      items: [
        "Event type and date",
        "Venue name or area in Riyadh",
        "Expected guest count (a range is fine)",
        "Preferred format: plated, buffet, canapés or breaks",
        "Event timings and service duration",
        "Dietary requirements or restrictions",
        "Whether service staff are needed",
        "Budget range, if you have one",
      ],
    },
    coordination: {
      heading: "How partner coordination works",
      paragraphs: [
        "SEM operates as a remote coordination platform. We do not own kitchens, equipment or service staff; catering is prepared and served by Saudi-based catering partners selected for your event.",
        "Our role is to qualify your brief, request suitable options, present them clearly, and keep communication in one place. Availability and pricing depend on the selected caterer, date, venue and final menu, and are confirmed in writing before you book.",
      ],
    },
    quality: {
      heading: "Quality and control considerations",
      items: [
        { title: "Clear written scope", desc: "Menu, quantities, staffing and timings are captured in the quotation." },
        { title: "Venue compatibility", desc: "Venue catering rules and kitchen access are checked before options are presented." },
        { title: "Dietary handling", desc: "Allergies and dietary needs are passed to the caterer in writing." },
        { title: "Tastings where offered", desc: "For larger bookings, ask whether a tasting is possible before sign-off." },
      ],
    },
    useCases: {
      heading: "Typical catering requests",
      items: [
        { title: "Corporate office opening", desc: "A canapé and mocktail reception with service staff for a two-to-three-hour window." },
        { title: "One-day conference", desc: "Arrival coffee, two breaks and a networking lunch, timed to the agenda." },
        { title: "Wedding reception", desc: "A seated or buffet dinner with service planned for each hall where required." },
        { title: "Majlis or family gathering", desc: "Arabic coffee, dates and a home-style buffet for an evening gathering." },
      ],
    },
    feature: {
      image: "/riyadh_luxury_reception_people.webp",
      alt: "Hotel ballroom set for a seated banquet with chandeliers, dressed tables and a decorated stage",
      caption: "Representative setup — seated banquet in a hotel ballroom",
    },
    riyadh: {
      heading: "Event catering across Riyadh",
      paragraphs: [
        "Most catering enquiries SEM handles are for Riyadh: hotel ballrooms and conference venues, private halls, offices and outdoor venues. Hotel venues often require in-house catering, while private halls and outdoor sites usually allow external caterers — one of the first things we check.",
        "If your event also needs production, entertainment or guest arrival services, SEM can coordinate them under the same enquiry.",
      ],
      links: [
        { label: "All event services in Riyadh", href: "/locations/riyadh" },
        { label: "Corporate event venues in Riyadh", href: "/blog/best-corporate-event-venues-riyadh-2026" },
      ],
    },
    faqs: [
      { q: "Does SEM prepare the food itself?", a: "No. SEM is a coordination platform. Food is prepared and served by Saudi-based catering partners selected for your event. SEM manages the enquiry, options, quotation and communication." },
      { q: "Is the catering halal?", a: "Halal is the standard for catering in Saudi Arabia. Include any additional dietary requirements in your enquiry so they are passed to the caterer at the request stage." },
      { q: "How much does event catering cost in Riyadh?", a: "It depends on guest count, menu, service style, duration, staffing and venue conditions. SEM does not publish fixed prices because they change per caterer and date; you receive a specific quotation once your requirements are confirmed." },
      { q: "Can you arrange catering at a hotel venue?", a: "Many hotels require their in-house catering. SEM checks the venue's policy first; where external catering is allowed, we request options from suitable partners." },
      { q: "Can service staff be included?", a: "Yes, where the catering partner supplies waiters, buffet attendants or beverage staff as part of the package. Staffing levels are shown in the quotation." },
      { q: "Are live cooking stations available?", a: "Where the selected caterer offers them and the venue permits on-site cooking. Mention it in your enquiry and SEM will check which options are realistic." },
      { q: "How early should I enquire?", a: "As early as possible, especially for weekends, Ramadan and peak event seasons. Short-notice requests can be checked, but options may be limited." },
      { q: "Can catering be combined with other event services?", a: "Yes. SEM can coordinate catering alongside décor, entertainment, valet parking and VIP transportation in one enquiry." },
    ],
    related: [
      { title: "Valet Parking", href: "/services/valet-parking", desc: "Guest arrival and parking for catered events.", image: "/services/valet_golf_cart_guest_mobility.webp" },
      { title: "Event Decoration", href: "/services/event-decoration", desc: "Table styling, florals and venue décor.", image: "/saudi_event_decor_2026.webp" },
      { title: "Entertainment", href: "/services/entertainment", desc: "Live music and performers for dinners and receptions.", image: "/services/live_band_musicians_saudi.webp" },
      { title: "VIP Transportation", href: "/services/vip-transportation", desc: "Chauffeured transfers for VIP guests.", image: "/services/vip_airport_chauffeur_riyadh.webp" },
    ],
    form: {
      heading: "Request catering options",
      subheading: "Share your event details. SEM reviews the brief, checks suitable catering partners and comes back with options and next steps.",
      submitLabel: "Request Catering Options",
      serviceOptions: [
        "Corporate Event Catering",
        "Conference / Coffee Break Catering",
        "Executive Meeting Catering",
        "Wedding Catering",
        "VIP / Majlis Hospitality",
        "Private Event Catering",
        "Canapés & Reception",
        "Buffet Catering",
        "Live Cooking Stations",
        "Exhibition Catering",
        "Outdoor Event Catering",
        "Not sure — please advise",
      ],
      eventTypeOptions: ["Corporate Event", "Conference / Seminar", "Wedding / Engagement", "Exhibition", "Office Opening / Launch", "Private / Family Gathering", "Other"],
      guestCountLabel: "Guest Count",
      messagePlaceholder: "Event timings, menu preferences, venue catering rules you know of, anything else we should pass to the caterer...",
      fields: [
        { name: "serviceStyle", label: "Meal / service style", type: "select", options: ["Plated / seated", "Buffet", "Canapés / finger food", "Coffee breaks & refreshments", "Mixed / not sure"] },
        { name: "duration", label: "Service duration", type: "select", options: ["Up to 2 hours", "2–4 hours", "Half day", "Full day", "Multi-day"] },
        { name: "dietary", label: "Dietary requirements", type: "text", placeholder: "e.g. vegetarian options, nut allergy" },
        { name: "staff", label: "Service staff needed?", type: "select", options: ["Yes", "No", "Not sure"] },
        { name: "venueKitchen", label: "Venue type", type: "select", options: ["Hotel / venue with in-house catering", "Private hall", "Office / corporate premises", "Outdoor venue", "Private residence", "Not confirmed yet"] },
      ],
      whatsappText: "Hi SEM, I'd like catering options for an event in Riyadh.",
    },
  },
};
