import type { ServiceCategory } from "./types";

// Metadata for this route lives in app/[locale]/services/valet-parking/layout.tsx
// (indexed EN + AR) — intentionally not duplicated here.
const fields = [
  { name: "startTime", label: "Start time", type: "time" as const },
  { name: "duration", label: "Event duration", type: "select" as const, options: ["Up to 3 hours", "3–6 hours", "Full day", "Multi-day"] },
  { name: "vehicles", label: "Estimated vehicles (if known)", type: "select" as const, options: ["Under 50", "50–150", "150–300", "300+", "Not sure"] },
  { name: "vip", label: "VIP guests?", type: "select" as const, options: ["Yes", "No", "Not sure"] },
  { name: "parking", label: "Parking arrangement", type: "select" as const, options: ["Venue car park", "Nearby / overflow lot", "Street / limited", "Not sure"] },
  { name: "addOns", label: "Golf cart / accessibility needs", type: "select" as const, options: ["Golf carts", "Wheelchair / accessibility support", "Both", "None", "Not sure"] },
];

const IMG = {
  hotel: "/services/transport/chauffeur-hotel-arrival-riyadh-evening.webp",
  arrival: "/services/transport/vip-chauffeur-arrival-riyadh-exhibition-centre.webp",
  golf: "/services/valet_golf_cart_guest_mobility.webp",
  wedding: "/riyadh_luxury_reception_people.webp",
  summit: "/services/premium_corporate_summit_hero.webp",
  shuttle: "/services/transport/delegate-shuttle-riyadh-convention-centre.webp",
};

const serviceOptions = ["Wedding Valet", "Corporate Event Valet", "Gala / VIP Valet", "Conference Valet", "Exhibition Valet", "Hotel Event Valet", "Private / Family Event Valet", "Golf Cart / Mobility Support", "Not sure — please advise"];
const eventTypeOptions = ["Wedding", "Corporate Event / Gala", "Conference / Exhibition", "Hotel Event", "Private Event", "VIP Event", "Other"];

export const valetParking: ServiceCategory = {
  slug: "valet-parking",
  source: "valet_parking_page",
  serviceType: "Event Valet Parking",
  en: {
    name: "Valet Parking",
    hero: {
      badge: "Valet Parking & Guest Arrival · Riyadh",
      title: "Event Valet Parking",
      highlight: "in Riyadh",
      subtitle:
        "Uniformed valet teams, secure key handling and smooth guest arrivals for weddings, galas and corporate events. Tell us your venue, guest count and arrival window — SEM coordinates a suitable Saudi-based valet partner.",
      image: "/services/valet_golf_cart_guest_mobility.webp",
      imageAlt: "Golf cart driver transferring a guest from the parking area to a lit venue entrance at dusk",
    },
    snapshot: [
      { label: "Service type", value: "Guest arrival & parking" },
      { label: "Best for", value: "Weddings · Galas · VIP" },
      { label: "Location", value: "Riyadh & major Saudi cities" },
      { label: "Quote", value: "Guest-flow based" },
    ],
    answer: {
      question: "How does event valet parking work in Riyadh?",
      answer:
        "Event valet parking means uniformed staff receive guests' cars at the entrance, park them securely and return them at departure, so guests arrive and leave without searching for parking. With SEM, you share the venue, date, guest count, expected vehicles and arrival window; SEM coordinates a suitable Saudi-based valet partner, confirms staffing and the parking plan, and keeps one point of contact through to the event.",
    },
    intro: [
      "Arrival is the first thing guests experience and departure is the last. A slow queue at the gate or a long wait for cars undoes a lot of good work inside the venue.",
      "SEM does not employ valet staff directly. We qualify your guest flow — vehicles, arrival window, parking space, VIPs — and coordinate an established Saudi-based valet partner whose team size and setup suit your event.",
    ],
    capabilities: {
      heading: "What the valet service covers",
      lead: "Each valet plan is built around your venue and guest flow:",
      items: [
        { icon: "door", title: "Guest arrival management", desc: "Greeting, door service and a clear drop-off point so arrivals keep moving." },
        { icon: "users", title: "Uniformed valet teams", desc: "Professional, uniformed staff sized to your expected vehicles and arrival peak." },
        { icon: "key", title: "Secure key handling", desc: "Ticketed key management and a controlled retrieval process." },
        { icon: "crown", title: "VIP arrival support", desc: "Priority parking, a dedicated valet point and discreet handling for VIPs." },
        { icon: "route", title: "Parking flow coordination", desc: "Drop-off zones, parking areas and traffic flow planned with the venue." },
        { icon: "clock", title: "Departure management", desc: "Staffing for the departure peak so guests aren't left waiting." },
      ],
    },
    subServices: {
      heading: "Valet services by event type",
      lead: "One enquiry covers all of these. Tell us the event and SEM coordinates the right valet setup.",
      items: [
        { title: "Wedding Valet", desc: "Smooth arrivals for families and guests, with separate entrances where needed.", useCase: "Receptions, engagements", image: "/riyadh_luxury_reception_people.webp", imageAlt: "Hotel ballroom prepared for a wedding reception", href: "/services/weddings" },
        { title: "VIP & Gala Valet", desc: "Priority parking, a dedicated counter and discreet VIP handling.", useCase: "Galas, award nights, VIP dinners", image: "/services/vip_airport_chauffeur_riyadh.webp", imageAlt: "Chauffeur holding a car door open for a guest at a hotel entrance", href: "/services/vip-transportation" },
        { title: "Golf-Cart Guest Mobility", desc: "Golf carts to move guests from distant parking to the entrance.", useCase: "Large venues, outdoor sites", image: "/services/valet_golf_cart_guest_mobility.webp", imageAlt: "Golf cart carrying a guest to a venue entrance at dusk" },
        { icon: "building", title: "Corporate Event Valet", desc: "Peak-arrival staffing for galas, launches and summits.", href: "/services/corporate-events" },
        { icon: "users", title: "Conference & Exhibition Valet", desc: "High-throughput delegate and visitor parking.", href: "/services/conferences" },
        { icon: "building", title: "Hotel & Venue Event Valet", desc: "Event valet integrated with the property's own arrival flow." },
        { icon: "star", title: "Private Event Valet", desc: "Valet for private homes, farms and family gatherings." },
        { icon: "accessibility", title: "Accessibility Assistance", desc: "Wheelchair and mobility support at arrival and departure." },
        { icon: "sparkles", title: "Premium Add-ons", desc: "Luggage help, umbrella service and car care where the partner offers them." },
        { icon: "users", title: "Exhibition Valet", desc: "Visitor and exhibitor parking across show days.", href: "/services/exhibitions" },
        { icon: "crown", title: "Executive Guest Arrival", desc: "Greeting and priority handling for executives." },
        { icon: "star", title: "VIP Arrival Coordination", desc: "A dedicated lane and point for VIP cars.", href: "/services/vip-transportation" },
        { icon: "route", title: "Guest Parking Flow", desc: "Drop-off, parking and retrieval zones planned." },
        { icon: "key", title: "Key Management", desc: "Ticketed key control and retrieval." },
        { icon: "clock", title: "Arrival / Departure Management", desc: "Staffing for both peaks, not just arrivals." },
        { icon: "map", title: "Parking Coordination", desc: "Car park and overflow arrangements with the venue." },
        { icon: "door", title: "Venue Entrance Coordination", desc: "Entrance flow aligned with greeters and security." },
        { icon: "users", title: "High-Volume Arrival Planning", desc: "Peak planning for large weddings and summits." },
        { icon: "users", title: "Family Event Valet", desc: "Valet for family gatherings and celebrations." },
        { icon: "flower", title: "Luxury Wedding Arrival", desc: "A premium arrival experience for wedding guests.", href: "/services/weddings" },
        { icon: "building", title: "Corporate Dinner / Gala Arrival", desc: "Staged arrivals for dinners and award nights.", href: "/services/corporate-events" },
      ],
    },
    eventIntents: {
      heading: "Valet parking for every type of event",
      lead: "Arrival needs change with the event. Choose an event type to see what a valet plan typically covers.",
      items: [
        { id: "wedding", title: "Weddings", image: IMG.wedding, imageAlt: "Wedding reception ballroom", points: ["Guest arrival and greeting", "Key management", "Parking flow", "VIP / family entrance", "Separate entrances where needed", "Departure flow at the end of the night"], links: [{ label: "Wedding planning", href: "/services/weddings" }, { label: "Wedding guest transportation", href: "/services/vip-transportation" }] },
        { id: "corporate", title: "Corporate", image: IMG.summit, imageAlt: "Corporate summit lounge", points: ["Executive arrival", "Employee and guest parking", "Parking coordination with the venue", "Venue entrance flow"], links: [{ label: "Corporate events", href: "/services/corporate-events" }, { label: "Executive transportation", href: "/services/vip-transportation" }] },
        { id: "gala", title: "Gala / VIP", image: IMG.hotel, imageAlt: "Chauffeur at an illuminated hotel entrance at night", points: ["VIP arrival lane", "Priority parking for executive vehicles", "Dedicated valet point", "Smooth, staged departure"], links: [{ label: "Luxury & VIP events", href: "/services/luxury-vip-events" }, { label: "VIP transportation", href: "/services/vip-transportation" }] },
        { id: "conference", title: "Conferences", image: IMG.shuttle, imageAlt: "Delegates arriving at a convention centre", points: ["Delegate arrival peaks", "Scheduled arrivals by session", "Venue parking coordination", "Accessibility support"], links: [{ label: "Conference coordination", href: "/services/conferences" }, { label: "Delegate shuttles", href: "/services/vip-transportation" }] },
        { id: "hotel", title: "Hotel events", image: IMG.arrival, imageAlt: "Chauffeur holding a car door outside a Riyadh venue", points: ["Hotel event arrivals", "Ballroom / event entrance", "Guest flow alongside hotel traffic", "Vehicle hand-off and retrieval"], links: [{ label: "Event catering", href: "/services/event-catering" }, { label: "Event décor", href: "/services/event-decoration" }] },
        { id: "outdoor", title: "Outdoor / Farm venues", image: IMG.golf, imageAlt: "Golf cart moving a guest to a venue entrance", points: ["Valet coordination at large sites", "Golf cart support where available", "Guest movement from distant parking", "Lighting and walkways checked with the venue"], links: [{ label: "Event lighting", href: "/services/event-lighting" }, { label: "Private celebrations", href: "/services/birthday-party" }] },
      ],
    },
    journeys: {
      heading: "How a smooth arrival is planned",
      lead: "Valet is one link in the guest journey. Each step links to the service that covers it.",
      flows: [
        {
          title: "Wedding arrival",
          steps: [
            { label: "Hotel / Home", note: "Family departs" },
            { label: "VIP Transport", note: "Bridal party & family", href: "/services/vip-transportation" },
            { label: "Drop-off", note: "Clear arrival point" },
            { label: "Valet", note: "Keys & parking", href: "/services/valet-parking#options" },
            { label: "Entrance", note: "Greeting & décor", href: "/services/event-decoration" },
            { label: "Event", note: "Catering & music", href: "/services/event-catering" },
            { label: "Departure", note: "Cars returned in order" },
          ],
        },
        {
          title: "Corporate gala arrival",
          steps: [
            { label: "Executive cars", note: "Chauffeured VIPs", href: "/services/vip-transportation" },
            { label: "VIP lane", note: "Priority drop-off" },
            { label: "Guest valet", note: "Self-driving guests" },
            { label: "Red carpet", note: "Entrance & photos" },
            { label: "Gala", note: "Stage, sound, lighting", href: "/services/event-production" },
            { label: "Staged departure", note: "No long waits" },
          ],
        },
      ],
    },
    options: {
      heading: "Valet service options",
      lead: "Add-ons and service levels that can be included in a valet plan.",
      note: "Available subject to date, venue and partner availability. Team size is proposed by the partner for your guest flow.",
      items: [
        { title: "Uniformed valet team", desc: "Professional valet staff for arrival and departure.", suits: "All events", icon: "users" },
        { title: "Valet counter & key control", desc: "A valet point with ticketed key management.", suits: "Weddings, galas, hotels", icon: "key" },
        { title: "VIP arrival lane", desc: "Priority drop-off and parking for VIPs.", suits: "Galas, VIP dinners", icon: "crown" },
        { title: "Golf cart mobility", desc: "Guest transfers between parking and entrance.", suits: "Large and outdoor venues", image: IMG.golf, imageAlt: "Golf cart carrying a guest to a venue entrance" },
        { title: "Accessibility support", desc: "Wheelchair and mobility assistance.", suits: "Family events, conferences", icon: "accessibility" },
        { title: "Guest care add-ons", desc: "Luggage help, umbrellas and door service.", suits: "Hotels, VIP events", icon: "sparkles" },
        { title: "Vehicle care", desc: "Car washing and detailing during longer events.", suits: "Full-day events", icon: "wrench" },
        { title: "Traffic & zone planning", desc: "Drop-off zones and parking flow planned with the venue.", suits: "High-volume arrivals", icon: "route" },
      ],
    },
    builder: true,
    flow: {
      heading: "How a valet plan is sized",
      lead: "Staffing and layout follow these five inputs.",
      steps: [
        { label: "Guest count", detail: "Total attendees" },
        { label: "Expected vehicles", detail: "Self-drive vs. driven guests" },
        { label: "Arrival window", detail: "How tightly guests arrive" },
        { label: "Valet staffing", detail: "Team size for peak flow" },
        { label: "Parking flow", detail: "Drop-off, parking, retrieval" },
      ],
    },
    idealFor: {
      heading: "Ideal for",
      items: [
        { title: "Weddings", desc: "Family and guest arrivals.", href: "/services/weddings" },
        { title: "Corporate events", desc: "Galas, launches, summits.", href: "/services/corporate-events" },
        { title: "Gala dinners", desc: "Formal arrivals and departures." },
        { title: "Hotel events", desc: "Event peaks beyond hotel capacity." },
        { title: "Private events", desc: "Homes, farms and private venues." },
        { title: "VIP events", desc: "Priority and discreet handling.", href: "/services/luxury-vip-events" },
        { title: "Exhibitions", desc: "Visitor and exhibitor parking.", href: "/services/exhibitions" },
      ],
    },
    process: {
      heading: "How the valet service works",
      items: [
        { title: "Share event details", desc: "Venue, date, guest count and expected vehicles." },
        { title: "Confirm guest flow", desc: "Arrival window, parking space, VIPs and departure peak." },
        { title: "SEM coordinates a provider", desc: "A suitable Saudi-based valet partner for your date." },
        { title: "Requirements confirmed", desc: "Staffing, layout, add-ons and timings in writing." },
        { title: "Execution coordinated", desc: "SEM stays your point of contact on the day." },
      ],
    },
    quoteFactors: {
      heading: "What affects valet parking pricing?",
      lead: "Valet pricing follows staffing and logistics:",
      items: [
        { title: "Expected vehicles", desc: "The main driver of team size." },
        { title: "Arrival peak", desc: "Tight arrival windows need more staff at once." },
        { title: "Event duration", desc: "Hours on site, including departure." },
        { title: "Parking distance", desc: "Remote lots may need runners or golf carts." },
        { title: "VIP requirements", desc: "Dedicated counters and priority handling." },
        { title: "Add-ons", desc: "Golf carts, accessibility support, umbrellas, car care." },
      ],
    },
    clientChecklist: {
      heading: "What information is needed for a valet quote?",
      items: [
        "City and venue name",
        "Event date, start time and duration",
        "Guest count",
        "Estimated number of vehicles",
        "Available parking (venue car park, overflow lot)",
        "Number of VIP arrivals",
        "Any add-ons: golf carts, accessibility support",
      ],
    },
    coordination: {
      heading: "How partner coordination works",
      paragraphs: [
        "SEM is a remote coordination platform. Valet staff and equipment are provided by an established Saudi-based valet partner selected for your event — SEM does not employ the valet team directly.",
        "SEM qualifies your guest flow, confirms staffing and the parking plan with the partner, presents one quotation and stays your point of contact. Availability and pricing depend on the date, venue and requirements, and are confirmed in writing before you book.",
      ],
    },
    quality: {
      heading: "Quality and control considerations",
      items: [
        { title: "Staffing in writing", desc: "Team size, hours and add-ons are listed in the quotation." },
        { title: "Venue coordination", desc: "Drop-off zones and parking areas are agreed with the venue in advance." },
        { title: "Key control", desc: "Ticketed key handling and a controlled retrieval point." },
        { title: "Departure planning", desc: "Staffing is planned for the departure peak, not just arrivals." },
      ],
    },
    useCases: {
      heading: "Typical valet requests",
      items: [
        { title: "Hotel wedding reception", desc: "A valet team and dedicated family entrance for an evening reception." },
        { title: "Corporate gala", desc: "Peak-arrival staffing for a 7–8 pm arrival window with VIP priority parking." },
        { title: "Private farm event", desc: "Golf carts moving guests from a field car park to the venue." },
        { title: "Two-day exhibition", desc: "Visitor parking flow across show days with fixed operating hours." },
      ],
    },
    feature: {
      image: IMG.hotel,
      alt: "Chauffeur in white gloves holding a car door at an illuminated hotel entrance at night",
      caption: "Representative setup — attended guest arrival at a hotel entrance",
    },
    riyadh: {
      heading: "Event valet across Riyadh",
      paragraphs: [
        "Riyadh events are car-led: most guests drive or are driven, and arrival peaks for weddings and galas are tight. Hotel ballrooms, private halls and farm venues each need a different parking plan — which is why SEM confirms the parking layout with the venue before staffing is quoted.",
        "Valet pairs naturally with VIP transportation for guests who shouldn't drive themselves, and with catering and entertainment for the event inside.",
      ],
      links: [
        { label: "All event services in Riyadh", href: "/locations/riyadh" },
        { label: "VIP transportation", href: "/services/vip-transportation" },
      ],
    },
    faqs: [
      { q: "Do you provide valet parking for weddings in Riyadh?", a: "Yes. SEM coordinates uniformed valet teams for weddings, scaled to the venue's guest count and parking layout, including separate entrances where needed." },
      { q: "Who provides the valet staff?", a: "Valet staff are provided by an established Saudi-based valet partner selected for your event. SEM coordinates the booking, requirements and communication." },
      { q: "How many valet staff do I need?", a: "It depends on expected vehicles, how tightly guests arrive and parking distance. Share these details and the partner proposes a team size for your peak." },
      { q: "How is key and vehicle security handled?", a: "Valet teams use ticketed key management and a controlled retrieval process so vehicles are tracked and returned efficiently." },
      { q: "Can valet staff assist elderly guests or guests with disabilities?", a: "Yes. Wheelchair and mobility assistance at arrival and departure can be included." },
      { q: "Can golf carts be arranged for large venues?", a: "Yes, golf carts can be included to move guests between distant parking areas and the entrance." },
      { q: "How much does event valet cost in Riyadh?", a: "Pricing depends on vehicles, arrival peak, duration, parking distance and add-ons. SEM does not publish fixed prices; you receive a specific quotation once the requirement is confirmed." },
      { q: "How far in advance should valet be booked?", a: "We recommend at least 2–3 weeks ahead, and earlier for peak wedding season and Riyadh Season." },
      { q: "Can valet parking be coordinated with VIP transportation?", a: "Yes. SEM can coordinate chauffeured arrivals for VIP guests alongside a valet team for self-driving guests, so the whole arrival is planned as one." },
      { q: "What information is needed for a valet quote?", a: "City and venue, event date, start time and duration, guest count, estimated vehicles if known, VIP arrivals, the parking arrangement and any golf cart or accessibility needs." },
    ],
    related: [
      { title: "VIP Transportation", href: "/services/vip-transportation", desc: "Chauffeured transfers for VIP guests.", image: "/services/vip_airport_chauffeur_riyadh.webp" },
      { title: "Event Catering", href: "/services/event-catering", desc: "Catering for weddings and galas.", image: "/services/saudi_gala_table_alcohol_free.webp" },
      { title: "Weddings", href: "/services/weddings", desc: "Wedding planning and coordination.", image: "/riyadh_luxury_reception_people.webp" },
      { title: "Corporate Events", href: "/services/corporate-events", desc: "Galas, launches and company events.", image: "/services/premium_corporate_summit_hero.webp" },
    ],
    form: {
      heading: "Request a valet quote",
      subheading: "Share your venue and guest flow. SEM confirms availability with a suitable valet partner and comes back with a staffing plan and quote.",
      submitLabel: "Request Valet Quote",
      serviceOptions,
      eventTypeOptions,
      guestCountLabel: "Guest Count",
      messagePlaceholder: "Arrival window, separate entrances, VIP details, anything the venue has told you about parking...",
      fields,
      whatsappText: "Hi SEM, I'd like a quote for event valet parking in Riyadh.",
    },
  },
  ar: {
    name: "خدمة الفاليه",
    hero: {
      badge: "الفاليه واستقبال الضيوف · الرياض",
      title: "خدمة فاليه الفعاليات",
      highlight: "في الرياض",
      subtitle:
        "فرق فاليه موحّدة الزي، وإدارة آمنة للمفاتيح، ووصول سلس للضيوف في حفلات الزفاف والحفلات الفاخرة وفعاليات الشركات. شاركنا الموقع وعدد الضيوف ووقت الوصول — وتنسّق إدارة الفعاليات السعودية مع شريك فاليه مناسب في المملكة.",
      image: "/services/valet_golf_cart_guest_mobility.webp",
      imageAlt: "عربة جولف تنقل ضيفة من موقف السيارات إلى مدخل قاعة مضاءة عند الغروب",
    },
    snapshot: [
      { label: "نوع الخدمة", value: "استقبال الضيوف والوقوف" },
      { label: "الأنسب لـ", value: "الأعراس · الحفلات · كبار الشخصيات" },
      { label: "الموقع", value: "الرياض والمدن الرئيسية" },
      { label: "عرض السعر", value: "حسب تدفّق الضيوف" },
    ],
    answer: {
      question: "كيف تعمل خدمة فاليه الفعاليات في الرياض؟",
      answer:
        "خدمة الفاليه تعني أن طاقمًا موحّد الزي يستلم سيارات الضيوف عند المدخل، ويوقفها بأمان، ويعيدها عند المغادرة، فيصل الضيوف ويغادرون دون البحث عن موقف. مع إدارة الفعاليات السعودية، تشاركنا الموقع والتاريخ وعدد الضيوف والمركبات المتوقعة ووقت الوصول؛ فننسّق مع شريك فاليه مناسب في المملكة، ونؤكد عدد الطاقم وخطة الوقوف، ونبقى نقطة تواصلك حتى يوم الفعالية.",
    },
    intro: [
      "الوصول هو أول ما يعيشه الضيف، والمغادرة آخر ما يتذكره. طابور بطيء عند البوابة أو انتظار طويل للسيارة يُفسد الكثير مما بُذل داخل القاعة.",
      "لا توظّف إدارة الفعاليات السعودية طاقم الفاليه مباشرة؛ بل ندرس تدفّق ضيوفك — المركبات، ووقت الوصول، ومساحة الوقوف، وكبار الشخصيات — وننسّق مع شريك فاليه سعودي معتمد يناسب حجم فريقه وتجهيزاته فعاليتك.",
    ],
    capabilities: {
      heading: "ما تشمله خدمة الفاليه",
      lead: "تُبنى كل خطة فاليه حول موقعك وتدفّق ضيوفك:",
      items: [
        { icon: "door", title: "إدارة وصول الضيوف", desc: "استقبال، وفتح الأبواب، ونقطة إنزال واضحة لاستمرار حركة الوصول." },
        { icon: "users", title: "فرق فاليه موحّدة الزي", desc: "طاقم محترف بحجم يناسب عدد المركبات وذروة الوصول." },
        { icon: "key", title: "إدارة آمنة للمفاتيح", desc: "نظام تذاكر للمفاتيح وآلية استرجاع منظّمة." },
        { icon: "crown", title: "دعم وصول كبار الشخصيات", desc: "أولوية وقوف، ونقطة فاليه مخصّصة، وتعامل متكتّم." },
        { icon: "route", title: "تنظيم تدفّق الوقوف", desc: "مناطق الإنزال والوقوف وحركة المرور بالتنسيق مع الموقع." },
        { icon: "clock", title: "إدارة المغادرة", desc: "طاقم كافٍ لذروة المغادرة حتى لا ينتظر الضيوف." },
      ],
    },
    subServices: {
      heading: "خدمات الفاليه حسب نوع الفعالية",
      lead: "طلب واحد يشمل كل ذلك. أخبرنا بنوع الفعالية وننسّق الإعداد المناسب.",
      items: [
        { title: "فاليه حفلات الزفاف", desc: "وصول سلس للعائلات والضيوف، مع مداخل منفصلة عند الحاجة.", useCase: "حفلات الاستقبال والخطوبة", image: "/riyadh_luxury_reception_people.webp", imageAlt: "قاعة فندقية مجهّزة لحفل زفاف", href: "/services/weddings" },
        { title: "فاليه الحفلات وكبار الشخصيات", desc: "أولوية وقوف، وكاونتر مخصّص، وتعامل متكتّم مع كبار الشخصيات.", useCase: "الحفلات الفاخرة وليالي الجوائز", image: "/services/vip_airport_chauffeur_riyadh.webp", imageAlt: "سائق يفتح باب السيارة لضيفة عند مدخل فندق", href: "/services/vip-transportation" },
        { title: "عربات الجولف لتنقّل الضيوف", desc: "عربات جولف لنقل الضيوف من المواقف البعيدة إلى المدخل.", useCase: "المواقع الكبيرة والخارجية", image: "/services/valet_golf_cart_guest_mobility.webp", imageAlt: "عربة جولف تقل ضيفة إلى مدخل القاعة" },
        { icon: "building", title: "فاليه فعاليات الشركات", desc: "طاقم لذروة الوصول في الحفلات والإطلاقات والقمم.", href: "/services/corporate-events" },
        { icon: "users", title: "فاليه المؤتمرات والمعارض", desc: "إدارة وقوف عالية السعة للمندوبين والزوّار.", href: "/services/conferences" },
        { icon: "building", title: "فاليه الفنادق والقاعات", desc: "فاليه للفعالية مندمج مع تدفّق وصول الموقع." },
        { icon: "star", title: "فاليه المناسبات الخاصة", desc: "للمنازل والمزارع والتجمعات العائلية." },
        { icon: "accessibility", title: "مساعدة ذوي الاحتياجات", desc: "كراسي متحركة ودعم التنقّل عند الوصول والمغادرة." },
        { icon: "sparkles", title: "خدمات إضافية متميّزة", desc: "مساعدة بالأمتعة، ومظلات، وعناية بالسيارات حين يوفّرها الشريك." },
        { icon: "users", title: "فاليه المعارض", desc: "وقوف الزوّار والعارضين طوال أيام العرض.", href: "/services/exhibitions" },
        { icon: "crown", title: "وصول الضيوف التنفيذيين", desc: "استقبال وتعامل بأولوية للتنفيذيين." },
        { icon: "star", title: "تنسيق وصول كبار الشخصيات", desc: "مسار ونقطة مخصّصان لسيارات كبار الشخصيات.", href: "/services/vip-transportation" },
        { icon: "route", title: "تدفّق وقوف الضيوف", desc: "تخطيط مناطق الإنزال والوقوف والاسترجاع." },
        { icon: "key", title: "إدارة المفاتيح", desc: "تحكّم بالمفاتيح بنظام التذاكر واسترجاع منظّم." },
        { icon: "clock", title: "إدارة الوصول والمغادرة", desc: "طاقم للذروتين، لا للوصول فقط." },
        { icon: "map", title: "تنسيق المواقف", desc: "ترتيبات المواقف الأساسية والإضافية مع الموقع." },
        { icon: "door", title: "تنسيق مدخل القاعة", desc: "تدفّق الدخول بالتنسيق مع المستقبلين والأمن." },
        { icon: "users", title: "تخطيط الوصول بأعداد كبيرة", desc: "تخطيط الذروة للأعراس والقمم الكبيرة." },
        { icon: "users", title: "فاليه المناسبات العائلية", desc: "فاليه للتجمعات والاحتفالات العائلية." },
        { icon: "flower", title: "وصول فاخر لحفلات الزفاف", desc: "تجربة وصول مميّزة لضيوف الزفاف.", href: "/services/weddings" },
        { icon: "building", title: "وصول عشاء وحفلات الشركات", desc: "وصول مرتّب لحفلات العشاء وليالي الجوائز.", href: "/services/corporate-events" },
      ],
    },
    eventIntents: {
      heading: "فاليه لكل نوع من الفعاليات",
      lead: "تختلف احتياجات الوصول بحسب الفعالية. اختر نوع الفعالية لترى ما تشمله خطة الفاليه عادةً.",
      items: [
        { id: "wedding", title: "الأعراس", image: IMG.wedding, imageAlt: "قاعة استقبال زفاف", points: ["استقبال الضيوف والترحيب", "إدارة المفاتيح", "تنظيم تدفّق الوقوف", "مدخل لكبار الشخصيات والعائلة", "مداخل منفصلة عند الحاجة", "تنظيم المغادرة في نهاية الحفل"], links: [{ label: "تخطيط الأعراس", href: "/services/weddings" }, { label: "نقل ضيوف الزفاف", href: "/services/vip-transportation" }] },
        { id: "corporate", title: "الشركات", image: IMG.summit, imageAlt: "صالة قمة شركات", points: ["وصول التنفيذيين", "وقوف الموظفين والضيوف", "تنسيق المواقف مع القاعة", "تنظيم الدخول إلى القاعة"], links: [{ label: "فعاليات الشركات", href: "/services/corporate-events" }, { label: "النقل التنفيذي", href: "/services/vip-transportation" }] },
        { id: "gala", title: "الحفلات / كبار الشخصيات", image: IMG.hotel, imageAlt: "سائق عند مدخل فندق مضاء ليلًا", points: ["مسار وصول لكبار الشخصيات", "أولوية وقوف للمركبات التنفيذية", "نقطة فاليه مخصّصة", "مغادرة سلسة ومرتّبة"], links: [{ label: "فعاليات كبار الشخصيات", href: "/services/luxury-vip-events" }, { label: "نقل كبار الشخصيات", href: "/services/vip-transportation" }] },
        { id: "conference", title: "المؤتمرات", image: IMG.shuttle, imageAlt: "مندوبون يصلون إلى مركز مؤتمرات", points: ["ذروة وصول المندوبين", "وصول مجدول حسب الجلسات", "تنسيق مواقف القاعة", "دعم ذوي الاحتياجات"], links: [{ label: "تنسيق المؤتمرات", href: "/services/conferences" }, { label: "حافلات المندوبين", href: "/services/vip-transportation" }] },
        { id: "hotel", title: "فعاليات الفنادق", image: IMG.arrival, imageAlt: "سائق يمسك باب سيارة أمام قاعة في الرياض", points: ["وصول ضيوف فعاليات الفنادق", "مدخل القاعة / الفعالية", "تدفّق الضيوف بجانب حركة الفندق", "تسليم المركبات واسترجاعها"], links: [{ label: "تموين الفعاليات", href: "/services/event-catering" }, { label: "ديكور الفعاليات", href: "/services/event-decoration" }] },
        { id: "outdoor", title: "المواقع الخارجية / المزارع", image: IMG.golf, imageAlt: "عربة جولف تنقل ضيفة إلى مدخل القاعة", points: ["تنسيق الفاليه في المواقع الكبيرة", "عربات جولف حين تتوفّر", "نقل الضيوف من المواقف البعيدة", "مراجعة الإضاءة والممرات مع الموقع"], links: [{ label: "إضاءة الفعاليات", href: "/services/event-lighting" }, { label: "الاحتفالات الخاصة", href: "/services/birthday-party" }] },
      ],
    },
    journeys: {
      heading: "كيف يُخطَّط وصول سلس",
      lead: "الفاليه حلقة في رحلة الضيف. كل خطوة ترتبط بالخدمة التي تغطيها.",
      flows: [
        {
          title: "وصول الزفاف",
          steps: [
            { label: "الفندق / المنزل", note: "انطلاق العائلة" },
            { label: "نقل كبار الشخصيات", note: "موكب العروسين والعائلة", href: "/services/vip-transportation" },
            { label: "نقطة الإنزال", note: "نقطة وصول واضحة" },
            { label: "الفاليه", note: "المفاتيح والوقوف", href: "/services/valet-parking#options" },
            { label: "المدخل", note: "الاستقبال والديكور", href: "/services/event-decoration" },
            { label: "الحفل", note: "الضيافة والموسيقى", href: "/services/event-catering" },
            { label: "المغادرة", note: "إعادة السيارات بالترتيب" },
          ],
        },
        {
          title: "وصول حفل الشركات",
          steps: [
            { label: "السيارات التنفيذية", note: "كبار الشخصيات بسائق", href: "/services/vip-transportation" },
            { label: "مسار كبار الشخصيات", note: "إنزال بأولوية" },
            { label: "فاليه الضيوف", note: "للقادمين بسياراتهم" },
            { label: "السجادة الحمراء", note: "الدخول والتصوير" },
            { label: "الحفل", note: "المسرح والصوت والإضاءة", href: "/services/event-production" },
            { label: "مغادرة مرتّبة", note: "دون انتظار طويل" },
          ],
        },
      ],
    },
    options: {
      heading: "خيارات خدمة الفاليه",
      lead: "إضافات ومستويات خدمة يمكن تضمينها في خطة الفاليه.",
      note: "متاحة حسب التاريخ والموقع وتوفّر الشريك. يقترح الشريك حجم الفريق وفق تدفّق ضيوفك.",
      items: [
        { title: "فريق فاليه موحّد الزي", desc: "طاقم فاليه محترف للوصول والمغادرة.", suits: "جميع الفعاليات", icon: "users" },
        { title: "كاونتر فاليه وإدارة المفاتيح", desc: "نقطة فاليه مع نظام تذاكر للمفاتيح.", suits: "الأعراس والحفلات والفنادق", icon: "key" },
        { title: "مسار لكبار الشخصيات", desc: "إنزال ووقوف بأولوية لكبار الشخصيات.", suits: "الحفلات وعشاء كبار الشخصيات", icon: "crown" },
        { title: "تنقّل بعربات الجولف", desc: "نقل الضيوف بين المواقف والمدخل.", suits: "المواقع الكبيرة والخارجية", image: IMG.golf, imageAlt: "عربة جولف تقل ضيفة إلى مدخل القاعة" },
        { title: "دعم ذوي الاحتياجات", desc: "كراسي متحركة ومساعدة في التنقّل.", suits: "المناسبات العائلية والمؤتمرات", icon: "accessibility" },
        { title: "خدمات رعاية الضيوف", desc: "مساعدة بالأمتعة ومظلات وفتح الأبواب.", suits: "الفنادق وفعاليات كبار الشخصيات", icon: "sparkles" },
        { title: "العناية بالمركبات", desc: "غسيل وتلميع السيارات في الفعاليات الطويلة.", suits: "فعاليات اليوم الكامل", icon: "wrench" },
        { title: "تخطيط الحركة والمناطق", desc: "مناطق الإنزال وتدفّق الوقوف بالتنسيق مع الموقع.", suits: "الوصول بأعداد كبيرة", icon: "route" },
      ],
    },
    builder: true,
    flow: {
      heading: "كيف يُحدَّد حجم خطة الفاليه",
      lead: "يُبنى الطاقم والتخطيط على هذه المدخلات الخمسة.",
      steps: [
        { label: "عدد الضيوف", detail: "إجمالي الحضور" },
        { label: "المركبات المتوقعة", detail: "من يقود ومن يُقاد" },
        { label: "نافذة الوصول", detail: "مدى تزامن وصول الضيوف" },
        { label: "طاقم الفاليه", detail: "حجم الفريق لساعة الذروة" },
        { label: "تدفّق الوقوف", detail: "إنزال، وقوف، استرجاع" },
      ],
    },
    idealFor: {
      heading: "الأنسب لـ",
      items: [
        { title: "حفلات الزفاف", desc: "وصول العائلات والضيوف.", href: "/services/weddings" },
        { title: "فعاليات الشركات", desc: "الحفلات والإطلاقات والقمم.", href: "/services/corporate-events" },
        { title: "حفلات العشاء الرسمية", desc: "وصول ومغادرة منظّمان." },
        { title: "فعاليات الفنادق", desc: "ذروة تفوق طاقة الفندق." },
        { title: "المناسبات الخاصة", desc: "المنازل والمزارع والمواقع الخاصة." },
        { title: "فعاليات كبار الشخصيات", desc: "أولوية وتعامل متكتّم.", href: "/services/luxury-vip-events" },
        { title: "المعارض", desc: "وقوف الزوّار والعارضين.", href: "/services/exhibitions" },
      ],
    },
    process: {
      heading: "كيف تعمل الخدمة",
      items: [
        { title: "شارك تفاصيل الفعالية", desc: "الموقع، والتاريخ، وعدد الضيوف، والمركبات المتوقعة." },
        { title: "تأكيد تدفّق الضيوف", desc: "وقت الوصول، ومساحة الوقوف، وكبار الشخصيات، وذروة المغادرة." },
        { title: "التنسيق مع مزوّد مناسب", desc: "شريك فاليه سعودي مناسب ومتاح في تاريخك." },
        { title: "تأكيد المتطلبات", desc: "الطاقم والتخطيط والإضافات والأوقات كتابيًا." },
        { title: "تنسيق التنفيذ", desc: "نبقى نقطة تواصلك يوم الفعالية." },
      ],
    },
    quoteFactors: {
      heading: "ما الذي يؤثر على سعر خدمة الفاليه؟",
      lead: "يتحدد السعر بحسب الطاقم واللوجستيات:",
      items: [
        { title: "عدد المركبات", desc: "العامل الأساسي لحجم الفريق." },
        { title: "ذروة الوصول", desc: "النوافذ الضيقة تحتاج طاقمًا أكبر في وقت واحد." },
        { title: "مدة الفعالية", desc: "ساعات العمل بما فيها المغادرة." },
        { title: "بُعد المواقف", desc: "المواقف البعيدة قد تحتاج عدّائين أو عربات جولف." },
        { title: "متطلبات كبار الشخصيات", desc: "كاونترات مخصّصة وتعامل بأولوية." },
        { title: "الإضافات", desc: "عربات جولف، ودعم ذوي الاحتياجات، ومظلات، وعناية بالسيارات." },
      ],
    },
    clientChecklist: {
      heading: "ما المعلومات المطلوبة لعرض سعر الفاليه؟",
      items: [
        "اسم الموقع وعنوانه",
        "تاريخ الفعالية ووقت البداية والنهاية",
        "عدد الضيوف",
        "العدد التقريبي للمركبات",
        "المواقف المتاحة (موقف القاعة، موقف إضافي)",
        "عدد كبار الشخصيات",
        "أي إضافات: عربات جولف، دعم ذوي الاحتياجات",
      ],
    },
    coordination: {
      heading: "كيف يعمل التنسيق مع الشركاء",
      paragraphs: [
        "إدارة الفعاليات السعودية منصة تنسيق عن بُعد. يوفّر طاقم الفاليه وتجهيزاته شريك فاليه سعودي معتمد يُختار لفعاليتك — ولا نوظّف فريق الفاليه مباشرة.",
        "نحن ندرس تدفّق ضيوفك، ونؤكد الطاقم وخطة الوقوف مع الشريك، ونقدّم عرض سعر واحدًا، ونبقى نقطة تواصلك. يعتمد التوفّر والسعر على التاريخ والموقع والمتطلبات، ويُؤكَّدان كتابيًا قبل الحجز.",
      ],
    },
    quality: {
      heading: "اعتبارات الجودة والتحكم",
      items: [
        { title: "الطاقم موثّق كتابيًا", desc: "حجم الفريق والساعات والإضافات مذكورة في عرض السعر." },
        { title: "التنسيق مع الموقع", desc: "مناطق الإنزال والوقوف متفق عليها مع الموقع مسبقًا." },
        { title: "التحكم بالمفاتيح", desc: "مفاتيح بنظام التذاكر ونقطة استرجاع منظّمة." },
        { title: "تخطيط المغادرة", desc: "الطاقم مخطّط لذروة المغادرة لا الوصول فقط." },
      ],
    },
    useCases: {
      heading: "طلبات فاليه نموذجية",
      items: [
        { title: "حفل زفاف في فندق", desc: "فريق فاليه ومدخل مخصّص للعائلة لحفل مسائي." },
        { title: "حفل شركة", desc: "طاقم لذروة وصول بين 7 و8 مساءً مع أولوية لكبار الشخصيات." },
        { title: "مناسبة في مزرعة خاصة", desc: "عربات جولف تنقل الضيوف من الموقف إلى مكان الحفل." },
        { title: "معرض لمدة يومين", desc: "تنظيم وقوف الزوّار طوال أيام العرض بساعات تشغيل محددة." },
      ],
    },
    feature: {
      image: IMG.hotel,
      alt: "سائق بقفازات بيضاء يمسك باب سيارة أمام مدخل فندق مضاء ليلًا",
      caption: "إعداد نموذجي — استقبال الضيوف عند مدخل فندق",
    },
    riyadh: {
      heading: "خدمة الفاليه في أنحاء الرياض",
      paragraphs: [
        "الفعاليات في الرياض تعتمد على السيارات: معظم الضيوف يقودون أو يُقادون، وذروة الوصول في الأعراس والحفلات ضيقة. لكل قاعة فندقية أو قاعة خاصة أو مزرعة خطة وقوف مختلفة — ولهذا نؤكد مخطط الوقوف مع الموقع قبل تسعير الطاقم.",
        "تتكامل خدمة الفاليه مع النقل الفاخر لكبار الشخصيات، ومع الضيافة والترفيه داخل الفعالية.",
      ],
      links: [
        { label: "جميع خدمات الفعاليات في الرياض", href: "/locations/riyadh" },
        { label: "النقل الفاخر لكبار الشخصيات", href: "/services/vip-transportation" },
      ],
    },
    faqs: [
      { q: "هل تقدّمون خدمة فاليه لحفلات الزفاف في الرياض؟", a: "نعم. ننسّق فرق فاليه موحّدة الزي لحفلات الزفاف بحسب عدد الضيوف ومخطط الوقوف، مع مداخل منفصلة عند الحاجة." },
      { q: "من يوفّر طاقم الفاليه؟", a: "يوفّر الطاقم شريك فاليه سعودي معتمد يُختار لفعاليتك، وتتولى إدارة الفعاليات السعودية تنسيق الحجز والمتطلبات والتواصل." },
      { q: "كم عدد أفراد الفاليه الذي أحتاجه؟", a: "يعتمد على عدد المركبات ومدى تزامن الوصول وبُعد المواقف. شاركنا هذه التفاصيل ويقترح الشريك حجم الفريق المناسب للذروة." },
      { q: "كيف تُدار سلامة المفاتيح والمركبات؟", a: "تستخدم فرق الفاليه نظام تذاكر للمفاتيح وآلية استرجاع منظّمة لتتبّع المركبات وإعادتها بكفاءة." },
      { q: "هل يمكن مساعدة كبار السن وذوي الاحتياجات؟", a: "نعم. يمكن إضافة المساعدة بالكراسي المتحركة ودعم التنقّل عند الوصول والمغادرة." },
      { q: "هل يمكن توفير عربات جولف للمواقع الكبيرة؟", a: "نعم، يمكن إضافة عربات جولف لنقل الضيوف بين المواقف البعيدة والمدخل." },
      { q: "كم تكلفة خدمة الفاليه للفعاليات في الرياض؟", a: "يعتمد السعر على عدد المركبات وذروة الوصول والمدة وبُعد المواقف والإضافات. لا ننشر أسعارًا ثابتة؛ ستحصل على عرض سعر محدد بعد تأكيد المتطلبات." },
      { q: "قبل كم من الوقت يجب حجز الفاليه؟", a: "نوصي بالحجز قبل 2-3 أسابيع على الأقل، وأبكر خلال مواسم الأعراس وموسم الرياض." },
      { q: "هل يمكن تنسيق الفاليه مع نقل كبار الشخصيات؟", a: "نعم. يمكننا تنسيق وصول كبار الضيوف بسائق إلى جانب فريق فاليه للضيوف القادمين بسياراتهم، ليُخطَّط الوصول كاملًا كوحدة واحدة." },
      { q: "ما المعلومات المطلوبة لعرض سعر الفاليه؟", a: "المدينة والقاعة، وتاريخ الفعالية، ووقت البدء والمدة، وعدد الضيوف، والعدد التقريبي للمركبات إن عُرف، ووصول كبار الشخصيات، وترتيب المواقف، وأي حاجة لعربات جولف أو دعم ذوي الاحتياجات." },
    ],
    related: [
      { title: "النقل الفاخر لكبار الشخصيات", href: "/services/vip-transportation", desc: "نقل بسائق لضيوف كبار الشخصيات.", image: "/services/vip_airport_chauffeur_riyadh.webp" },
      { title: "تموين الفعاليات", href: "/services/event-catering", desc: "ضيافة للأعراس والحفلات.", image: "/services/saudi_gala_table_alcohol_free.webp" },
      { title: "حفلات الزفاف", href: "/services/weddings", desc: "تخطيط وتنسيق الأعراس.", image: "/riyadh_luxury_reception_people.webp" },
      { title: "فعاليات الشركات", href: "/services/corporate-events", desc: "حفلات وإطلاقات وفعاليات الشركات.", image: "/services/premium_corporate_summit_hero.webp" },
    ],
    form: {
      heading: "اطلب عرض سعر للفاليه",
      subheading: "شاركنا الموقع وتدفّق الضيوف، ونؤكد التوفّر مع شريك فاليه مناسب ونعود إليك بخطة الطاقم وعرض السعر.",
      submitLabel: "اطلب عرض الفاليه",
      serviceOptions,
      serviceOptionLabels: ["فاليه حفلات الزفاف", "فاليه فعاليات الشركات", "فاليه الحفلات وكبار الشخصيات", "فاليه المؤتمرات", "فاليه المعارض", "فاليه فعاليات الفنادق", "فاليه المناسبات الخاصة / العائلية", "عربات جولف / دعم التنقّل", "لست متأكدًا — أرجو النصيحة"],
      eventTypeOptions,
      eventTypeOptionLabels: ["زفاف", "فعالية شركة / حفل", "مؤتمر / معرض", "فعالية فندقية", "مناسبة خاصة", "فعالية كبار الشخصيات", "أخرى"],
      guestCountLabel: "عدد الضيوف",
      messageLabel: "متطلبات إضافية",
      messagePlaceholder: "وقت الوصول، المداخل المنفصلة، تفاصيل كبار الشخصيات، أي معلومات من الموقع عن المواقف...",
      fields: [
        { ...fields[0], displayLabel: "وقت البدء" },
        { ...fields[1], displayLabel: "مدة الفعالية", optionLabels: ["حتى 3 ساعات", "3–6 ساعات", "يوم كامل", "عدة أيام"] },
        { ...fields[2], displayLabel: "عدد المركبات المتوقع (إن عُرف)", optionLabels: ["أقل من 50", "50–150", "150–300", "أكثر من 300", "غير متأكد"] },
        { ...fields[3], displayLabel: "ضيوف من كبار الشخصيات؟", optionLabels: ["نعم", "لا", "غير متأكد"] },
        { ...fields[4], displayLabel: "ترتيب المواقف", optionLabels: ["موقف القاعة", "موقف قريب / إضافي", "مواقف محدودة", "غير متأكد"] },
        { ...fields[5], displayLabel: "عربات جولف / دعم ذوي الاحتياجات", optionLabels: ["عربات جولف", "كراسي متحركة / دعم التنقّل", "كلاهما", "لا شيء", "غير متأكد"] },
      ],
      whatsappText: "مرحبًا، أرغب في عرض سعر لخدمة فاليه لفعالية في الرياض.",
    },
  },
};
